name: Backpacks
version: '${project.version}'
main: me.paradis.backpacks.Backpacks
api-version: 1.18
authors: [ Paradis ]
description: backback plugin V0
commands:
  newbackpack:
    description: test command
    usage: /command